import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import QueryToastHandler from "@/components/widgets/query-toast-handler";
import SocketProvider from "@/lib/socket-provider";
import UserSocketMount from "@/lib/user-socket-mount";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Properly - Real Estate",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  const userId = session?.user?.id;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased`}
      >
        <SocketProvider />
        {userId && <UserSocketMount userId={Number(userId)} />}

        {/* Client component handles all query-to-toast logic */}
        <QueryToastHandler />

        {children}

        <Toaster
          position="top-right"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
