import Navbar from "@/components/Navbar/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Properties - Propely",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="bg-transparent text-black max-w-340 min-h-screen mx-auto px-5 flex flex-col">
            <Navbar />
            {children}
        </div>
    );
}
