export const chatslist = [
  {
    id: 1,
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'John Doe',
    property: 'Modern 2BHK Apartment',
    lastMessage: 'Hi! Is the apartment still available?',
    not_seen: false,
  },
  {
    id: 2,
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'Alice Johnson',
    property: 'Cozy Studio Flat',
    lastMessage: 'I am interested in visiting the property tomorrow.',
    not_seen: true,
  },
  {
    id: 3,
    avatar: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'Michael Smith',
    property: 'Luxury 3BHK Condo',
    lastMessage: 'Can you share more photos of the living room?',
    not_seen: true,
  },
  {
    id: 4,
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'Emma Brown',
    property: 'Beachside Villa',
    lastMessage: 'Thank you for the details!',
    not_seen: false,
  },
  {
    id: 5,
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'David Wilson',
    property: 'Penthouse Apartment',
    lastMessage: 'Is parking included in the rent?',
    not_seen: true,
  },
  {
    id: 6,
    avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'Sophia Taylor',
    property: 'Townhouse with Garden',
    lastMessage: 'Looks great! When can I schedule a visit?',
    not_seen: true,
  },
  {
    id: 7,
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'James Anderson',
    property: 'Downtown Loft',
    lastMessage: 'Do you offer any discounts?',
    not_seen: true,
  },
  {
    id: 8,
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'Olivia Martinez',
    property: 'Suburban 2BHK Apartment',
    lastMessage: 'Please send the full property details.',
    not_seen: true,
  },
  {
    id: 9,
    avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'William Clark',
    property: 'Modern Studio',
    lastMessage: 'Thank you for your quick response!',
    not_seen: false,
  },
  {
    id: 10,
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    name: 'Isabella Lewis',
    property: 'Luxury 4BHK Villa',
    lastMessage: 'Can I get the exact location of the property?',
    not_seen: true,
  },
];
